### PR TITLE
Add Atom feed to HTML head for autodiscovery

### PR DESCRIPTION
**Pull request by kejadlen**
Had to manually enter the feed link into my RSS reader, so here's a PR to in theory make autodiscovery work. It is untested, since I didn't want to build your whole site to make sure it worked.

### CODE REVIEW

**Comment by karpathy** [comment]
Looks good to me, thank you. Lets test in prod! :D

**Comment by kejadlen** [comment]
Looks like that should've been `/feed.xml` instead of `feed.xml`. Works on your homepage but not on the actual posts.

**Comment by karpathy** [comment]
Hm. Any idea how to fix?

**Comment by pquentin** [comment]
I think @kejadlen was referring to this: https://github.com/karpathy/karpathy.github.io/pull/17

**Pull request merged**
